# Generated by Django 4.1 on 2023-01-30 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更改时间')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, unique=True, verbose_name='产品名称')),
                ('number', models.CharField(max_length=255, verbose_name='产品编号')),
                ('act_amount', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='实际金额')),
                ('sal_amount', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='销售金额')),
                ('total_sales', models.IntegerField(default=0, verbose_name='总销售数量')),
                ('stock', models.IntegerField(default=0, verbose_name='库存')),
                ('source', models.IntegerField(default=0, verbose_name='来源渠道')),
                ('type', models.IntegerField(default=0, verbose_name='产品类型')),
            ],
            options={
                'verbose_name_plural': '产品表',
                'db_table': 'product',
            },
        ),
    ]
