# Generated by Django 4.1 on 2023-01-31 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='name',
            field=models.CharField(default=1, max_length=50, unique=True, verbose_name='产品名称'),
            preserve_default=False,
        ),
    ]
