# Generated by Django 3.2.9 on 2023-01-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_usermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmintableModel',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更改时间')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, unique=True, verbose_name='昵称')),
                ('password', models.CharField(max_length=255, verbose_name='密码')),
                ('telephone', models.CharField(max_length=22, unique=True, verbose_name='手机号码')),
                ('email', models.CharField(max_length=255, null=True, unique=True, verbose_name='邮箱')),
                ('level', models.IntegerField(default=1, verbose_name='等级')),
            ],
            options={
                'verbose_name_plural': '管理员',
                'db_table': 'admintable',
            },
        ),
    ]
