# Generated by Django 3.2.9 on 2023-01-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20230125_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='token',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
