# Generated by Django 3.2.9 on 2023-01-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_usermodel_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='token',
            field=models.CharField(max_length=300, null=True, unique=True, verbose_name='token'),
        ),
    ]
