# Generated by Django 4.1 on 2023-01-31 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20230131_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admintablemodel',
            name='name',
            field=models.CharField(default=1, max_length=50, unique=True, verbose_name='昵称'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='name',
            field=models.CharField(default=1, max_length=50, unique=True, verbose_name='昵称'),
            preserve_default=False,
        ),
    ]
